version: "3.8"
services:
    mongodb:
      image : mongo
      container_name: mongodb
      environment:
        - PUID=1000
        - PGID=1000
      volumes:
        - ./database:/data/db
      ports:
        - 27017:27017
      restart: unless-stopped
    app:
      image : midhunharikumar/plant-watering
      container_name: streamlit-ui
      environment:
        - PUID=1000
        - PGID=1000
      volumes:
        - ./database:/data/db
      ports:
        - 8501:8501
        - 8080:8080
        - 8000:8000
      restart: unless-stopped